### PR TITLE
Remove system parachain native runtimes after polkadot-sdk #1737

### PR DESCRIPTION
**Pull request by seadanda**
Changes related to #242.

Removes arguments for benchmarks for the following:
- `asset-hub-kusama` and `asset-hub-polkadot`
- `bridge-hub-kusama` and `bridge-hub-polkadot`
- `collectives-polkadot`
- `glutton-kusama`

Adds arguments for 
- `collectives-westend`
- `glutton-westend`

To be merged after [this PR](https://github.com/paritytech/polkadot-sdk/pull/1737) in `polkadot-sdk` and along with [this PR](https://github.com/paritytech/command-bot-scripts/pull/52) in `command-bot-scripts`

### CODE REVIEW

**Comment by mordamax** [comment]
you can skip this, as these are just mocks for tests, they can keep working with old data. 
or if you can - please update tests accordingly in guessCommand.spec.ts and parsePullRequestBotCommandLine.namedArgs.spec.ts

**Comment by seadanda** [comment]
Ah nice, I missed that they were tests. 

Thanks for the info, I'll take a look later and commit.

**Comment by seadanda** [comment]
unit tests passing, integration tests won't pass until [`command-bot-scripts#52`](https://github.com/paritytech/command-bot-scripts/pull/52) is merged from what I understand.

**Comment by mordamax** [comment]
@seadanda no all passed except lint 

```
/builds/parity/mirrors/command-bot/src/command-configs/__mocks__/fetchCommandsConfiguration.ts
  148:23  error  Replace `⏎··············label:·"Runtime",⏎··············type_one_of:·["bridge-hub-rococo"],⏎···········` with `·label:·"Runtime",·type_one_of:·["bridge-hub-rococo"]`  prettier/prettier
✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

i have just run `yarn fix` and pushed here, so should become 💚

**Comment by seadanda** [comment]
Ah nice, I can't actually see the job output as I don't have a Parity Gitlab account - thanks for fixing!

**Review by mordamax — APPROVED** [review]

**Pull request merged**
